spring:
  application:
    name: api-gateway-server
  cloud:
    config:
      discovery:
        serviceId: api-config-server
        enabled: true
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/checkout/**
          filters:
            - AddRequestHeader=X-Request-from, Gateway
            - AddResponseHeader=X-Response-Red, Blue
            - StripPrefix=-1
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products 
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/DigitalMoneyWallet
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
info:
  app:
    name: api-gateway-server
    description: API Gateway Server (from Github with love =)
    version: 1.0.0

# Set the base path for Actuator endpoints (descomentarlo si se quiere usar)
# management:
#   endpoints:
#     web:
#       base-path: /management

eureka:
  instance:
    instance-id: MMSTechnology-Personal-Admin:${spring.application.name}:${server.port}
    statusPageUrlPath: http://localhost:8085/actuator/info
    healthCheckUrlPath: http://localhost:8085/actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/
